[package]
name = "nvapi_sys"
version = "0.1.0"
edition = "2021"
description = "Updated NVAPI bindings"
documentation = "None"
homepage = "None"
repository = "None"
license = "None"
license_file = "None"

[lib]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.60.1"